services:
  - type: web
    name: koschei-web3-hub
    env: go
    rootDir: .
    buildCommand: |
      go mod vendor
      go build -mod=vendor -o app koschei/api/main.go
    startCommand: ./app
    envVars:
      - key: STATIC_DIR
        value: koschei/api/public
