services:
  - type: web
    name: koschei-web3-hub
    env: go
    rootDir: .
    buildCommand: |
      cd koschei/api
      go mod vendor
      go build -mod=vendor -o ../../app .
    startCommand: ./app
    envVars:
      - key: STATIC_DIR
        value: koschei/api/public
