import "server-only";
import { web3Db } from "@/lib/web3-db";

export const gameFactoryPositioning = "Koschei Web Game Factory turns a plain-language game prompt into a playable HTML5 demo and a Web3-ready package.";
export const gameFactorySafetyCopy = "Koschei Web3 Bridge MVP does not hold funds, manage private keys, connect wallets, deploy contracts, mint NFTs, sign transactions, or custody user assets. It only prepares game manifests, item schemas, NFT-compatible metadata, reward configs, and adapter configs.";

export type GFProject = { id:string; title:string|null; prompt:string; genre:string|null; visual_style:string|null; target_chain:string; status:string; metadata:Record<string,unknown>; created_at:string; updated_at:string };

type TemplateKey = "quest_arena_rpg"|"arena_survival"|"tower_defense"|"boss_fight"|"platformer"|"card_battle"|"resource_management"|"runner";

type GameBrief = {
  title:string; genre:string; style:string; prompt:string; template:TemplateKey;
  player:string; collectible:string; obstacle:string; goal:string; score_rule:string; game_over:string;
  labels:string[];
  web3:{ item_schema:string[]; nft_traits:string[]; reward_events:{key:string;reward:number}[]; notes?:string[] };
};

export function slugify(v:string){return v.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"") || "game-project";}

function hasAny(text:string, kws:string[]){return kws.some((k)=>text.includes(k));}

function pickTemplate(prompt:string, genre?:string|null):TemplateKey {
  const text = `${prompt} ${genre??""}`.toLowerCase();
  if (hasAny(text,["quest","badge","guardian","arena","chest","rpg","relic"])) return "quest_arena_rpg";
  if (hasAny(text,["survival","swarm","wave","enemies spawn","xp"])) return "arena_survival";
  if (hasAny(text,["tower defense","towers","base hp","waves","credits"])) return "tower_defense";
  if (hasAny(text,["boss","titan","boss hp","phases","meteors","laser"])) return "boss_fight";
  if (hasAny(text,["platformer","jump","platforms","spikes","portal"])) return "platformer";
  if (hasAny(text,["card","deck","turn","attack","shield"])) return "card_battle";
  if (hasAny(text,["colony","resource","mining","solar","shield","tycoon"])) return "resource_management";
  return "runner";
}

export function buildGameBrief(input:{title?:string|null;prompt:string;genre?:string|null;style?:string|null}):GameBrief{
  const title=input.title?.trim()||"Prompt Runner";const genre=input.genre?.trim()||"arcade";const style=input.style?.trim()||"minimal neon";
  const template = pickTemplate(input.prompt, input.genre);
  const common = {title,genre,style,prompt:input.prompt};
  if (template === "quest_arena_rpg") return {...common,template,player:"hero",collectible:"ancient badge",obstacle:"guardian enemy",goal:"collect 3 badges and unlock final chest",score_rule:"+15 per badge, +30 per guardian",game_over:"HP reaches 0",labels:["hero","ancient badge","guardian","final treasure chest"],web3:{item_schema:["ancient_badge","guardian_reward","final_treasure_chest"],nft_traits:["badge","quest"],reward_events:[{key:"collect_3_badges",reward:60},{key:"defeat_guardians",reward:40},{key:"unlock_final_chest",reward:100}],notes:["quest_progress_enabled"]}};
  if (template === "arena_survival") return {...common,template,player:"arena fighter",collectible:"xp orb",obstacle:"swarm enemy",goal:"survive escalating waves",score_rule:"+5 per orb, +20 per enemy",game_over:"HP reaches 0",labels:["arena fighter","xp orb","wave","enemy swarm"],web3:{item_schema:["xp_orb","wave_reward"],nft_traits:["survival","wave"],reward_events:[{key:"clear_wave",reward:25},{key:"collect_xp",reward:5}]}};
  if (template === "tower_defense") return {...common,template,player:"tower commander",collectible:"credits",obstacle:"path enemy",goal:"defend base across waves",score_rule:"+10 per defeated enemy",game_over:"Base HP reaches 0",labels:["tower slot","tower","enemy path","base hp"],web3:{item_schema:["tower_core","defense_credits"],nft_traits:["defense","tower"],reward_events:[{key:"defeat_enemy",reward:10},{key:"survive_wave",reward:30}]}};
  if (template === "boss_fight") return {...common,template,player:"player ship",collectible:"repair orb",obstacle:"titan boss",goal:"defeat boss before HP depletion",score_rule:"+20 per boss hit",game_over:"Player HP reaches 0",labels:["player ship","titan boss","boss hp","repair orb"],web3:{item_schema:["repair_orb","boss_core"],nft_traits:["boss","phase"],reward_events:[{key:"survive_phase",reward:30},{key:"defeat_boss",reward:150}]}};
  if (template === "platformer") return {...common,template,player:"platform explorer",collectible:"crystal",obstacle:"spike trap",goal:"collect crystals then reach portal",score_rule:"+10 per crystal",game_over:"HP reaches 0",labels:["platform","crystal","spike","portal"],web3:{item_schema:["crystal","portal_pass"],nft_traits:["platformer","jump"],reward_events:[{key:"collect_crystal",reward:10},{key:"reach_portal",reward:70}]}};
  if (template === "card_battle") return {...common,template,player:"duelist",collectible:"energy",obstacle:"enemy champion",goal:"reduce enemy HP to zero",score_rule:"+15 per winning turn",game_over:"Player HP reaches 0",labels:["attack card","shield card","energy blast","turn"],web3:{item_schema:["battle_card","energy_charge"],nft_traits:["card","turn"],reward_events:[{key:"win_turn",reward:15},{key:"win_match",reward:100}]}};
  if (template === "resource_management") return {...common,template,player:"colony overseer",collectible:"minerals",obstacle:"hazard event",goal:"grow colony while shielding base",score_rule:"+8 per production cycle",game_over:"Shield HP reaches 0",labels:["energy","minerals","shield hp","colony level"],web3:{item_schema:["mineral_cache","solar_grid"],nft_traits:["resource","colony"],reward_events:[{key:"upgrade_colony",reward:35},{key:"mine_resources",reward:8}]}};
  return {...common,template,player:"runner",collectible:"star shard",obstacle:"void spike",goal:"collect and survive",score_rule:"+10 per collectible",game_over:"3 collisions",labels:["runner","star shard","void spike"],web3:{item_schema:["star_shard","prompt_pioneer_badge"],nft_traits:["runner","arcade"],reward_events:[{key:"collect",reward:10},{key:"game_complete",reward:50}]}};
}

export function buildPreviewHtml(brief:Record<string,unknown>){
  const b = brief as GameBrief;
  const base = `<!doctype html><html><body style="margin:0;background:#070b16;color:#fff;font-family:system-ui"><canvas id=c width=760 height=420></canvas><script>const c=document.getElementById('c'),x=c.getContext('2d');const K={};onkeydown=e=>K[e.key]=1;onkeyup=e=>K[e.key]=0;let score=0,hp=5,tick=0;function txt(t,y){x.fillStyle='#fff';x.fillText(t,12,y);}function clamp(v,a,b){return Math.max(a,Math.min(b,v));}`;
  const end = `requestAnimationFrame(loop);}loop();</script></body></html>`;
  // lightweight manual fixtures: Guild Quest Arena -> quest_arena_rpg, Neon Swarm Survivor -> arena_survival, Void Titan Boss Fight -> boss_fight, Crystal Jump Quest -> platformer
  if (b.template==="quest_arena_rpg") return `${base}let p={x:60,y:220,w:20,h:20},badges=[{x:180,y:90,t:0},{x:330,y:300,t:0},{x:520,y:180,t:0}],guards=[{x:420,y:90},{x:620,y:280}],chest={x:680,y:200,open:0};function loop(){tick++;x.fillStyle='#0d1326';x.fillRect(0,0,760,420);x.font='14px sans-serif';txt('${b.title}',20);txt('Badges '+badges.filter(b=>b.t).length+'/3 HP '+hp+' Score '+score,40);if(K.ArrowUp)p.y-=3;if(K.ArrowDown)p.y+=3;if(K.ArrowLeft)p.x-=3;if(K.ArrowRight)p.x+=3;p.x=clamp(p.x,0,740);p.y=clamp(p.y,0,400);for(const g of guards){g.x+=Math.sin((tick+g.y)/30)*1.2;if(Math.abs(p.x-g.x)<16&&Math.abs(p.y-g.y)<16){hp--;p.x=60;p.y=220;}}for(const b of badges){if(!b.t&&Math.abs(p.x-b.x)<14&&Math.abs(p.y-b.y)<14){b.t=1;score+=15;}}if(badges.every(b=>b.t))chest.open=1;if(chest.open&&Math.abs(p.x-chest.x)<20&&Math.abs(p.y-chest.y)<20){txt('VICTORY: final chest unlocked',64);}x.fillStyle='#22d3ee';x.fillRect(p.x,p.y,20,20);x.fillStyle='#facc15';for(const b of badges){if(!b.t){x.beginPath();x.arc(b.x,b.y,8,0,6.28);x.fill();x.fillText('ancient badge',b.x-32,b.y-12);}}x.fillStyle='#ef4444';for(const g of guards){x.fillRect(g.x,g.y,18,18);x.fillText('guardian',g.x-16,g.y-8);}x.fillStyle=chest.open?'#86efac':'#6b7280';x.fillRect(chest.x,chest.y,26,20);x.fillStyle='#fff';x.fillText('final chest',chest.x-10,chest.y-8);if(hp<=0)txt('Game Over',64);${end}`;
  if (b.template==="arena_survival") return `${base}let p={x:370,y:210},en=[{x:80,y:70},{x:700,y:360},{x:700,y:60}],orbs=[{x:140,y:200},{x:560,y:150}],wave=1;function loop(){tick++;x.fillStyle='#0f172a';x.fillRect(0,0,760,420);if(tick%500===0){wave++;en.push({x:80+Math.random()*620,y:40+Math.random()*340});}txt('${b.title}',20);txt('Wave '+wave+' HP '+hp+' Score '+score,40);if(K.ArrowUp)p.y-=3;if(K.ArrowDown)p.y+=3;if(K.ArrowLeft)p.x-=3;if(K.ArrowRight)p.x+=3;p.x=clamp(p.x,0,740);p.y=clamp(p.y,0,400);for(const e of en){const dx=p.x-e.x,dy=p.y-e.y,m=Math.hypot(dx,dy)||1;e.x+=dx/m*1.2;e.y+=dy/m*1.2;if(Math.abs(dx)<14&&Math.abs(dy)<14){hp--;}}if(tick%15===0){for(const e of en){if(Math.abs(p.x-e.x)<90&&Math.abs(p.y-e.y)<20){score+=20;e.x=Math.random()*740;e.y=Math.random()*400;}}}for(const o of orbs){if(Math.abs(p.x-o.x)<12&&Math.abs(p.y-o.y)<12){score+=5;o.x=Math.random()*740;o.y=Math.random()*400;}}x.fillStyle='#38bdf8';x.fillRect(p.x,p.y,20,20);x.fillStyle='#f43f5e';for(const e of en)x.fillRect(e.x,e.y,16,16);x.fillStyle='#fde047';for(const o of orbs){x.beginPath();x.arc(o.x,o.y,6,0,6.28);x.fill();}if(hp<=0)txt('Game Over',64);${end}`;
  if (b.template==="tower_defense") return `${base}let credits=100,base=20,wave=1,en=[{t:0},{t:120}],towers=[{x:260,y:120},{x:450,y:300}],path=[[50,210],[700,210]];function loop(){tick++;x.fillStyle='#111827';x.fillRect(0,0,760,420);txt('${b.title}',20);txt('Credits '+credits+' Base HP '+base+' Wave '+wave+' Score '+score,40);x.strokeStyle='#64748b';x.beginPath();x.moveTo(50,210);x.lineTo(700,210);x.stroke();for(const t of towers){x.fillStyle='#60a5fa';x.fillRect(t.x,t.y,20,20);x.fillText('tower',t.x-4,t.y-8);}for(const e of en){e.t+=0.7+wave*0.03;const ex=50+e.t,ey=210;x.fillStyle='#ef4444';x.fillRect(ex,ey,14,14);for(const t of towers){if(Math.abs(t.x-ex)<120&&tick%25===0){score+=10;e.t=0;credits+=5;}}if(ex>700){base--;e.t=0;}}if(tick%700===0){wave++;en.push({t:0});credits+=20;}if(base<=0)txt('Game Over',64);${end}`;
  if (b.template==="boss_fight") return `${base}let p={x:120,y:210},boss={x:620,y:170,hp:240,phase:1},orbs=[{x:300,y:120}],shots=[];function loop(){tick++;x.fillStyle='#0b1020';x.fillRect(0,0,760,420);txt('${b.title}',20);txt('HP '+hp+' Score '+score+' Boss HP '+boss.hp,40);if(K.ArrowUp)p.y-=3;if(K.ArrowDown)p.y+=3;if(K.ArrowLeft)p.x-=3;if(K.ArrowRight)p.x+=3;p.x=clamp(p.x,0,740);p.y=clamp(p.y,0,400);if(tick%20===0)shots.push({x:p.x+18,y:p.y+10});for(const s of shots){s.x+=5;if(Math.abs(s.x-boss.x)<30&&Math.abs(s.y-boss.y)<50){boss.hp-=2;score+=20;}}if(tick%40===0){const hzY=40+Math.random()*340;if(Math.abs(p.y-hzY)<20)hp--;}for(const o of orbs){if(Math.abs(p.x-o.x)<14&&Math.abs(p.y-o.y)<14){hp=Math.min(5,hp+1);o.x=120+Math.random()*520;o.y=40+Math.random()*330;}}x.fillStyle='#22d3ee';x.fillRect(p.x,p.y,20,20);x.fillStyle='#a78bfa';x.fillRect(boss.x,boss.y,40,80);x.fillStyle='#f97316';for(const s of shots)x.fillRect(s.x,s.y,8,2);x.fillStyle='#fde047';for(const o of orbs){x.beginPath();x.arc(o.x,o.y,6,0,6.28);x.fill();}if(boss.hp<=0)txt('VICTORY',64);if(hp<=0)txt('Game Over',82);${end}`;
  if (b.template==="platformer") return `${base}let p={x:80,y:320,vy:0},plats=[[60,350,180],[280,290,160],[500,240,180]],cr=[{x:330,y:260,t:0},{x:580,y:210,t:0}],sp=[{x:250,y:350},{x:470,y:350}],portal={x:700,y:200};function onPlat(){return plats.some(a=>p.x>a[0]-10&&p.x<a[0]+a[2]&&p.y>=a[1]-22&&p.y<=a[1]-8);}function loop(){x.fillStyle='#111827';x.fillRect(0,0,760,420);txt('${b.title}',20);txt('Score '+score+' HP '+hp,40);if(K.ArrowLeft)p.x-=3;if(K.ArrowRight)p.x+=3;if((K.ArrowUp||K[' '])&&onPlat())p.vy=-7;p.vy+=0.35;p.y+=p.vy;if(onPlat()&&p.vy>0)p.vy=0;if(p.y>390){hp--;p.x=80;p.y=320;p.vy=0;}for(const s of sp){if(Math.abs(p.x-s.x)<14&&Math.abs(p.y-s.y)<18){hp--;}}for(const c of cr){if(!c.t&&Math.abs(p.x-c.x)<12&&Math.abs(p.y-c.y)<12){c.t=1;score+=10;}}x.fillStyle='#6b7280';for(const a of plats)x.fillRect(a[0],a[1],a[2],10);x.fillStyle='#22d3ee';x.fillRect(p.x,p.y,16,22);x.fillStyle='#facc15';for(const c of cr){if(!c.t){x.beginPath();x.arc(c.x,c.y,6,0,6.28);x.fill();}}x.fillStyle='#ef4444';for(const s of sp)x.fillRect(s.x,s.y,12,12);x.fillStyle='#34d399';x.fillRect(portal.x,portal.y,16,36);if(cr.every(c=>c.t)&&Math.abs(p.x-portal.x)<20&&Math.abs(p.y-portal.y)<30)txt('VICTORY',64);if(hp<=0)txt('Game Over',82);requestAnimationFrame(loop);}loop();</script></body></html>`;
  if (b.template==="card_battle") return `${base}let php=30,ehp=30,turn=1,energy=3,msg='';function card(name){if(name==='Attack'){ehp-=6;msg='Attack hit';}if(name==='Shield'){php=Math.min(30,php+4);msg='Shield up';}if(name==='Energy Blast'&&energy>0){ehp-=10;energy--;msg='Blast fired';}if(ehp>0){php-=4;}turn++;energy=Math.min(3,energy+1);}c.onclick=(e)=>{const r=c.getBoundingClientRect(),x0=e.clientX-r.left,y0=e.clientY-r.top;if(y0>340&&y0<390){if(x0<230)card('Attack');else if(x0<470)card('Shield');else card('Energy Blast');}};function loop(){x.fillStyle='#1f2937';x.fillRect(0,0,760,420);txt('${b.title}',20);txt('Player HP '+php+' Enemy HP '+ehp+' Turn '+turn+' Energy '+energy,40);x.fillStyle='#334155';x.fillRect(20,340,200,50);x.fillRect(260,340,200,50);x.fillRect(500,340,220,50);x.fillStyle='#fff';x.fillText('Attack',95,370);x.fillText('Shield',340,370);x.fillText('Energy Blast',565,370);txt(msg,70);if(ehp<=0)txt('VICTORY',90);if(php<=0)txt('Game Over',90);requestAnimationFrame(loop);}loop();</script></body></html>`;
  if (b.template==="resource_management") return `${base}let energy=20,minerals=10,shield=30,level=1,msg='';c.onclick=(e)=>{const r=c.getBoundingClientRect(),x0=e.clientX-r.left,y0=e.clientY-r.top;if(y0<330||y0>390)return;if(x0<250&&energy>=3){energy-=3;minerals+=5;msg='Mining surge';}else if(x0<500&&minerals>=8){minerals-=8;energy+=6;msg='Solar expanded';}else if(shield<40&&minerals>=5){minerals-=5;shield+=5;msg='Shield repaired';}if(minerals>30){level++;minerals-=12;msg='Colony level up';}};function loop(){if(tick++%120===0){energy++;minerals+=2;if(Math.random()<0.2){shield-=2;msg='Storm hit shield';}}x.fillStyle='#0f172a';x.fillRect(0,0,760,420);txt('${b.title}',20);txt('Energy '+energy+' Minerals '+minerals+' Shield HP '+shield+' Colony Lv '+level,40);txt(msg,64);x.fillStyle='#334155';x.fillRect(20,330,220,60);x.fillRect(270,330,220,60);x.fillRect(520,330,220,60);x.fillStyle='#fff';x.fillText('Mine',105,365);x.fillText('Build Solar',335,365);x.fillText('Repair Shield',565,365);if(shield<=0)txt('Game Over',90);requestAnimationFrame(loop);}loop();</script></body></html>`;
  return `<!doctype html><html><body><canvas id=c width=640 height=360></canvas><script>const c=document.getElementById('c'),x=c.getContext('2d');let p={x:80,y:180,w:20,h:20},col={x:300,y:120,r:8},obs={x:500,y:140,w:24,h:80},s=0,h=3,run=true,k={};onkeydown=e=>k[e.key]=1;onkeyup=e=>k[e.key]=0;function loop(){x.fillStyle='#0a0f1f';x.fillRect(0,0,640,360);x.fillStyle='#fff';x.fillText('${String(brief.title)}',10,20);x.fillText('Score '+s+' HP '+h,10,40);if(run){if(k.ArrowUp)p.y-=3;if(k.ArrowDown)p.y+=3;if(k.ArrowLeft)p.x-=3;if(k.ArrowRight)p.x+=3;p.x=Math.max(0,Math.min(620,p.x));p.y=Math.max(0,Math.min(340,p.y));obs.x-=2;if(obs.x<-30)obs.x=660;if((p.x-col.x)**2+(p.y-col.y)**2<220){s+=10;col.x=100+Math.random()*500;col.y=60+Math.random()*240;}if(p.x<obs.x+obs.w&&p.x+p.w>obs.x&&p.y<obs.y+obs.h&&p.y+p.h>obs.y){h--;obs.x=660;if(h<=0)run=false;}}x.fillStyle='#22d3ee';x.fillRect(p.x,p.y,p.w,p.h);x.fillStyle='#facc15';x.beginPath();x.arc(col.x,col.y,col.r,0,6.28);x.fill();x.fillStyle='#ef4444';x.fillRect(obs.x,obs.y,obs.w,obs.h);x.fillStyle='#9ca3af';x.fillText('runner',p.x-5,p.y-6);x.fillText('star shard',col.x-18,col.y-14);x.fillText('void spike',obs.x-16,obs.y-8);if(!run){x.fillStyle='#fff';x.fillText('Game Over - Press R to restart',220,180);if(k.r||k.R){s=0;h=3;run=true;p={x:80,y:180,w:20,h:20};}}requestAnimationFrame(loop);}loop();</script></body></html>`;
}

export function buildAssets(brief:Record<string,unknown>){const b=brief as GameBrief;const out=[{asset_type:"player",name:b.player,description:"Controllable character",rarity:"common",metadata:{template:b.template}}];
  if (b.template==="quest_arena_rpg") out.push({asset_type:"collectible",name:"ancient badge",description:"Quest badge collectible",rarity:"uncommon",metadata:{quest:true}},{asset_type:"enemy",name:"guardian enemy",description:"Arena guardian",rarity:"uncommon",metadata:{}},{asset_type:"reward",name:"final treasure chest",description:"Final quest chest",rarity:"rare",metadata:{unlock_after_badges:3}});
  else if (b.template==="arena_survival") out.push({asset_type:"collectible",name:"xp orb",description:"Experience orb",rarity:"common",metadata:{}},{asset_type:"enemy",name:"swarm enemy",description:"Chasing enemy",rarity:"common",metadata:{}},{asset_type:"reward",name:"wave cache",description:"Wave clear reward",rarity:"uncommon",metadata:{}});
  else if (b.template==="tower_defense") out.push({asset_type:"resource",name:"defense credits",description:"Build currency",rarity:"common",metadata:{}},{asset_type:"tower",name:"defense tower",description:"Path defense tower",rarity:"uncommon",metadata:{}},{asset_type:"enemy",name:"path enemy",description:"Marching enemy",rarity:"common",metadata:{}});
  else if (b.template==="boss_fight") out.push({asset_type:"boss",name:"titan boss",description:"Phase-based boss",rarity:"epic",metadata:{}},{asset_type:"collectible",name:"repair orb",description:"HP recovery orb",rarity:"common",metadata:{}},{asset_type:"reward",name:"boss core",description:"Boss defeat reward",rarity:"rare",metadata:{}});
  else if (b.template==="platformer") out.push({asset_type:"collectible",name:"crystal",description:"Platform collectible",rarity:"common",metadata:{}},{asset_type:"obstacle",name:"spike trap",description:"Damage hazard",rarity:"common",metadata:{}},{asset_type:"reward",name:"portal key",description:"Portal completion unlock",rarity:"uncommon",metadata:{}});
  else if (b.template==="card_battle") out.push({asset_type:"card",name:"attack card",description:"Damage card",rarity:"common",metadata:{}},{asset_type:"card",name:"shield card",description:"Defense card",rarity:"common",metadata:{}},{asset_type:"card",name:"energy blast",description:"Burst card",rarity:"uncommon",metadata:{}});
  else if (b.template==="resource_management") out.push({asset_type:"resource",name:"minerals",description:"Primary colony resource",rarity:"common",metadata:{}},{asset_type:"resource",name:"energy",description:"Power budget",rarity:"common",metadata:{}},{asset_type:"reward",name:"colony level crest",description:"Colony advancement reward",rarity:"uncommon",metadata:{}});
  else out.push({asset_type:"collectible",name:"star shard",description:"Score item",rarity:"common",metadata:{}},{asset_type:"obstacle",name:"void spike",description:"Avoid this",rarity:"uncommon",metadata:{}},{asset_type:"reward",name:"Prompt Pioneer Badge",description:"Generated MVP reward badge",rarity:"rare",metadata:{badge:true}});
  return out;
}
export function buildWeb3Package(project:GFProject, brief:Record<string,unknown>, assets:Record<string,unknown>[]){const b=brief as GameBrief;return{manifest:{project_id:project.id,title:b.title,target_chain:project.target_chain,generated_at:new Date().toISOString(),template:b.template,prompt:b.prompt},item_schema:{version:"1.0",items:assets.map((a)=>({type:a.asset_type,name:a.name,rarity:a.rarity})),recommended:b.web3.item_schema},nft_metadata:assets.map((a)=>({name:a.name,description:a.description,attributes:[{trait_type:"type",value:a.asset_type},{trait_type:"rarity",value:a.rarity},...b.web3.nft_traits.map((t)=>({trait_type:"tag",value:t}))]})),reward_config:{currency:"points",events:b.web3.reward_events},adapter_config:{chain:"arbitrum-sepolia",mode:"readiness-only",wallet_required:false,tx_signing:false,deploy:false}};}

export const gameFactoryDb={
 async createProject(input:{title?:string;prompt:string;genre?:string;visual_style?:string;target_chain?:string}){const q=`insert into game_factory_projects (title,prompt,genre,visual_style,target_chain) values ($1,$2,$3,$4,$5) returning id::text,title,prompt,genre,visual_style,target_chain,status,metadata,created_at::text,updated_at::text`;return (await web3Db.query<GFProject>(q,[input.title||null,input.prompt,input.genre||null,input.visual_style||null,input.target_chain||"arbitrum-sepolia"])).rows[0];},
 async listProjects(){return (await web3Db.query<GFProject>(`select id::text,title,prompt,genre,visual_style,target_chain,status,metadata,created_at::text,updated_at::text from game_factory_projects order by created_at desc`)).rows;},
 async getProject(id:string){return (await web3Db.query<GFProject>(`select id::text,title,prompt,genre,visual_style,target_chain,status,metadata,created_at::text,updated_at::text from game_factory_projects where id=$1 limit 1`,[id])).rows[0]??null;},
 async getBrief(id:string){return (await web3Db.query<{brief:Record<string,unknown>}>(`select brief from game_factory_briefs where project_id=$1 order by created_at desc limit 1`,[id])).rows[0]?.brief??null;},
 async getAssets(id:string){return (await web3Db.query<Record<string,unknown>>(`select asset_type,name,description,rarity,metadata from game_factory_assets where project_id=$1 order by created_at asc`,[id])).rows;},
 async getFiles(id:string){return (await web3Db.query<Record<string,unknown>>(`select file_path,file_type,content,metadata from game_factory_generated_files where project_id=$1 order by created_at asc`,[id])).rows;},
 async getWeb3Package(id:string){return (await web3Db.query<Record<string,unknown>>(`select manifest,item_schema,nft_metadata,reward_config,adapter_config from game_factory_web3_packages where project_id=$1 order by created_at desc limit 1`,[id])).rows[0]??null;}
};
