"use client";

import { useMemo, useState } from "react";
import { RiskScoreCard } from "@/components/RiskScoreCard";
import { SiteHeader } from "@/components/SiteHeader";

const items = [["anonymous", "Anonymous team?", true], ["roadmap", "Has roadmap?", false], ["repo", "Has public repo?", false], ["contract", "Has token contract?", false], ["audit", "Has audit?", false], ["utility", "Has utility?", false], ["website", "Has website?", false], ["community", "Has community?", false], ["disclaimer", "Has clear disclaimers?", false], ["custody", "Requires custody/private key?", true]] as const;
const fixes: Record<string, string> = { anonymous: "Publish verifiable team or accountable organization details.", roadmap: "Publish a clear roadmap with realistic milestones.", repo: "Link a maintained public repository or explain why code is private.", contract: "Document whether a token contract exists and link verified addresses when applicable.", audit: "Publish an independent security audit or clearly state that no audit is available.", utility: "Explain the product utility in specific, verifiable terms.", website: "Publish an official website with consistent project details.", community: "Provide official community channels and moderation guidance.", disclaimer: "Add clear product, risk, and non-investment disclaimers.", custody: "Remove custody and private-key requests. Use non-custodial wallet flows only." };

export default function Risk() {
  const [checks, setChecks] = useState<Record<string, boolean>>({});
  const result = useMemo(() => { let score = 20; for (const [key, , negative] of items) { if (negative && checks[key]) score += 25; if (!negative && !checks[key]) score += 7; } score = Math.min(100, score); const level: "Low" | "Medium" | "High" = checks.custody || score >= 70 ? "High" : score < 40 ? "Low" : "Medium"; const recommended = items.filter(([key, , negative]) => negative ? checks[key] : !checks[key]).map(([key]) => fixes[key]); return { score, level, fixes: recommended }; }, [checks]);
  return <main className="web3-page"><SiteHeader /><section className="mx-auto max-w-6xl px-5 py-16 lg:px-8"><p className="eyebrow">Trust transparency MVP</p><h1 className="mt-4 text-4xl font-black text-white">Risk & Trust Scanner</h1><div className="mt-9 grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div className="glass-card grid gap-3 p-6 sm:grid-cols-2">{items.map(([key, label]) => <label key={key} className="flex min-h-14 items-center gap-3 rounded-xl border border-white/10 bg-black/10 p-4 text-sm font-bold text-slate-300"><input type="checkbox" checked={Boolean(checks[key])} onChange={(event) => setChecks((current) => ({ ...current, [key]: event.target.checked }))} />{label}</label>)}</div><div><RiskScoreCard score={result.score} level={result.level} /><div className="glass-card mt-5 p-6"><h2 className="font-bold text-white">Recommended fixes</h2><ul className="mt-3 space-y-2 text-xs leading-5 text-slate-400">{result.fixes.length ? result.fixes.map((fix) => <li key={fix}>• {fix}</li>) : <li>• Maintain transparent project documentation and review it regularly.</li>}</ul></div></div></div><p className="mt-6 text-xs leading-5 text-slate-400">This is an informational risk checklist, not legal, financial, investment, or security advice.</p></section></main>;
}
