ALTER TABLE quote_requests
  ADD COLUMN IF NOT EXISTS whatsapp text,
  ADD COLUMN IF NOT EXISTS district text,
  ADD COLUMN IF NOT EXISTS full_delivery_address text,
  ADD COLUMN IF NOT EXISTS company_registration_status text,
  ADD COLUMN IF NOT EXISTS tax_number text,
  ADD COLUMN IF NOT EXISTS website text,
  ADD COLUMN IF NOT EXISTS business_type text,
  ADD COLUMN IF NOT EXISTS main_agricultural_activity text,
  ADD COLUMN IF NOT EXISTS crop_types text,
  ADD COLUMN IF NOT EXISTS current_processing_capacity text,
  ADD COLUMN IF NOT EXISTS working_hours_per_day text,
  ADD COLUMN IF NOT EXISTS expected_daily_volume text,
  ADD COLUMN IF NOT EXISTS material_moisture_note text,
  ADD COLUMN IF NOT EXISTS impurity_problem_description text,
  ADD COLUMN IF NOT EXISTS target_cleaning_result text,
  ADD COLUMN IF NOT EXISTS need_control_cabinet boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS need_fan_cyclone boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS need_bucket_elevator boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS need_spare_screen_sets boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS requested_screen_sets text,
  ADD COLUMN IF NOT EXISTS voltage_available text,
  ADD COLUMN IF NOT EXISTS installation_location_type text,
  ADD COLUMN IF NOT EXISTS available_space_dimensions text,
  ADD COLUMN IF NOT EXISTS special_requirements text,
  ADD COLUMN IF NOT EXISTS destination_port text,
  ADD COLUMN IF NOT EXISTS delivery_address_details text,
  ADD COLUMN IF NOT EXISTS forklift_or_unloading_available boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS customs_support_needed boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS target_budget text,
  ADD COLUMN IF NOT EXISTS expected_purchase_time text,
  ADD COLUMN IF NOT EXISTS quantity text;

CREATE TABLE IF NOT EXISTS supplier_cost_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  quote_request_id uuid REFERENCES quote_requests(id),
  supplier_name text,
  supplier_contact_name text,
  product_slug text,
  request_summary text NOT NULL,
  status text DEFAULT 'draft',
  sent_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS supplier_cost_breakdowns (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  quote_request_id uuid REFERENCES quote_requests(id),
  supplier_cost_request_id uuid REFERENCES supplier_cost_requests(id),
  currency text DEFAULT 'USD',
  machine_cost numeric,
  spare_parts_cost numeric,
  packing_cost numeric,
  inland_china_transport_cost numeric,
  sea_freight_cost numeric,
  destination_customs_cost numeric,
  destination_tax_cost numeric,
  destination_delivery_cost numeric,
  other_cost numeric,
  total_supplier_landed_cost numeric,
  trade_term text,
  destination text,
  supplier_notes text,
  validity_date date,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS customer_quotes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  quote_request_id uuid REFERENCES quote_requests(id),
  supplier_cost_breakdown_id uuid REFERENCES supplier_cost_breakdowns(id),
  currency text DEFAULT 'USD',
  internal_total_cost numeric NOT NULL,
  markup_type text DEFAULT 'fixed',
  markup_percent numeric,
  markup_amount numeric,
  final_customer_price numeric NOT NULL,
  gross_profit numeric,
  gross_margin_percent numeric,
  payment_terms_public text,
  delivery_terms_public text,
  quote_notes text,
  status text DEFAULT 'draft',
  sent_at timestamptz,
  valid_until date,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
