import Link from "next/link";
import { SiteHeader } from "@/components/SiteHeader";
import { Web3Card } from "@/components/Web3Card";
const modules = [["Game Asset Bridge","Structure portable game items and NFT-ready asset metadata."],["AI Metadata Studio","Generate clear asset, project, lore, pitch and launch copy."],["Risk & Trust Scanner","Turn project signals into a transparent risk checklist."],["ChainOps Dashboard","Check supported testnet RPC connectivity without exposing keys."]];
export default function Home() { return <main className="web3-page"><SiteHeader/><section className="relative overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_20%,rgba(37,99,235,.22),transparent_34%),radial-gradient(circle_at_20%_55%,rgba(124,58,237,.15),transparent_30%)]"/><div className="relative mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><p className="eyebrow">Web3 builder infrastructure</p><h1 className="mt-6 max-w-5xl text-5xl font-black tracking-tight text-white sm:text-7xl">Build ecosystem-ready Web3 outputs with <span className="bg-gradient-to-r from-blue-400 to-violet-400 bg-clip-text text-transparent">clarity and trust.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-300">AI-powered Web3 operating layer for builders, games, assets, metadata, launch pages, risk transparency and ecosystem growth.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/hub" className="web3-button">Open Web3 Hub →</Link><Link href="/builder" className="web3-button-secondary">Start Building</Link><Link href="/chains" className="web3-button-secondary">Check Chains</Link></div><div className="mt-14 grid gap-3 text-xs font-bold text-slate-400 sm:grid-cols-3"><span>✓ No custody</span><span>✓ No private key deployment</span><span>✓ No token trading</span></div></div></section>
<section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-5 lg:grid-cols-2"><Web3Card title="The builder problem" description="Web3 teams often navigate fragmented metadata, unclear trust signals, disconnected chain tooling and launch materials that are difficult to standardize."/><Web3Card title="The Koschei solution" description="Koschei combines builder tooling, structured outputs, infrastructure health checks and risk transparency in one safety-first operating layer."/></div></section>
<section className="border-y border-white/10 bg-slate-950/40"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="eyebrow">Core modules</p><h2 className="mt-3 text-3xl font-black text-white">One serious layer for the builder lifecycle.</h2><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{modules.map(([title,description])=><Web3Card key={title} title={title} description={description} status="Live MVP" href="/hub" action="Explore hub"/>)}</div></div></section>
<section className="mx-auto grid max-w-7xl gap-5 px-5 py-20 lg:grid-cols-2 lg:px-8"><Web3Card title="Chain / ecosystem layer" description="Support builders across Solana, Base, Arbitrum, Polygon, Optimism and Ethereum test environments with server-side provider checks and developer-ready outputs."/><Web3Card title="Safety-first architecture" description="Koschei does not trade tokens, custody funds or request seed phrases, deployer keys or wallet private keys. API secrets stay on the server."/></section>
<section className="mx-auto max-w-7xl px-5 pb-20 lg:px-8"><div className="glass-card p-8"><p className="eyebrow">Builder workflow</p><div className="mt-6 grid gap-5 md:grid-cols-4">{["Choose ecosystem", "Create asset metadata", "Review trust signals", "Export developer-ready JSON"].map((x,i)=><div key={x}><span className="text-sm font-black text-violet-300">0{i+1}</span><p className="mt-2 font-bold text-white">{x}</p></div>)}</div></div></section>
<section className="border-t border-white/10 bg-blue-600/10"><div className="mx-auto max-w-7xl px-5 py-20 text-center lg:px-8"><p className="eyebrow">Build with confidence</p><h2 className="mt-4 text-4xl font-black text-white">Create stronger Web3 project outputs.</h2><Link href="/builder" className="web3-button mt-7">Start Building →</Link></div></section></main> }
