"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { FeatureFlagBadge } from "@/components/FeatureFlagBadge";

type Row = Record<string, unknown>;
type Plan = Row & { id: string; name: string; price_try: number | string; output_quota: number | string; shopier_url: string; is_active: boolean };
const chainFlags: Record<string, string> = { FEATURE_SOLANA: "Solana", FEATURE_BASE: "Base", FEATURE_ARBITRUM: "Arbitrum", FEATURE_POLYGON: "Polygon", FEATURE_OPTIMISM: "Optimism", FEATURE_ETHEREUM: "Ethereum" };
const money = (value: unknown) => new Intl.NumberFormat("tr-TR", { style: "currency", currency: "TRY" }).format(Number(value));
const date = (value: unknown) => typeof value === "string" ? new Date(value).toLocaleString("tr-TR") : "—";
function Cell({ children }: { children: React.ReactNode }) { return <td className="whitespace-nowrap px-3 py-3 text-xs text-slate-300">{children ?? "—"}</td>; }
function Empty({ columns, label }: { columns: number; label: string }) { return <tr><td colSpan={columns} className="px-3 py-5 text-center text-xs text-slate-500">{label}</td></tr>; }
function TableShell({ title, children }: { title: string; children: React.ReactNode }) { return <section className="glass-card overflow-hidden"><h2 className="border-b border-white/10 px-5 py-4 font-bold text-white">{title}</h2><div className="overflow-x-auto">{children}</div></section>; }

export function AdminDashboard({ flags }: { flags: Record<string, boolean> }) {
  const [loggedIn, setLoggedIn] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const [plans, setPlans] = useState<Plan[]>([]); const [paymentRequests, setPaymentRequests] = useState<Row[]>([]); const [entitlements, setEntitlements] = useState<Row[]>([]); const [outputs, setOutputs] = useState<Row[]>([]);
  const loadData = useCallback(async () => { setLoading(true); setError(""); try { const responses = await Promise.all([fetch("/api/admin/plans"), fetch("/api/admin/orders"), fetch("/api/admin/entitlements"), fetch("/api/admin/outputs")]); if (responses.some((response) => !response.ok)) throw new Error("Admin data request failed."); const [planData, requestData, entitlementData, outputData] = await Promise.all(responses.map((response) => response.json())); setPlans(planData.plans); setPaymentRequests(requestData.paymentRequests); setEntitlements(entitlementData.entitlements); setOutputs(outputData.outputs); } catch { setError("Could not load Neon admin data. Confirm the owner session, DATABASE_URL, and migration status."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timeout = window.setTimeout(() => { void fetch("/api/admin/session").then((response) => { setLoggedIn(response.ok); if (response.ok) void loadData(); }); }, 0); return () => window.clearTimeout(timeout); }, [loadData]);
  async function login(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const data = new FormData(event.currentTarget); try { const response = await fetch("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: data.get("email"), password: data.get("password") }) }); if (!response.ok) throw new Error("Login failed."); setLoggedIn(true); await loadData(); } catch { setError("Login failed. Unauthorized access is not permitted."); } }
  async function logout() { await fetch("/api/admin/logout", { method: "POST" }); setLoggedIn(false); setError(""); }
  async function review(id: unknown, status: "manual_verified" | "rejected") { if (typeof id !== "string") return; setLoading(true); setError(""); try { const response = await fetch("/api/admin/orders", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status }) }); if (!response.ok) throw new Error("Review failed."); await loadData(); } catch { setError("Could not review the payment request. Confirm the migration and database connection."); setLoading(false); } }
  if (!loggedIn) return <form onSubmit={login} className="glass-card mx-auto mt-9 max-w-md space-y-4 p-6"><p className="text-sm font-bold leading-6 text-rose-200">Owner-only area. Unauthorized access is not permitted.</p><label className="web3-label">Email<input name="email" type="email" className="web3-input" required /></label><label className="web3-label">Password<input name="password" type="password" className="web3-input" required /></label><button className="web3-button">Sign in</button>{error && <p role="alert" className="text-xs leading-5 text-rose-300">{error}</p>}</form>;
  const enabledChains = Object.entries(chainFlags).filter(([flag]) => flags[flag]).map(([, label]) => label); const enabledFlags = Object.entries(flags).filter(([, enabled]) => enabled);
  return <div className="mt-9 space-y-6"><p className="rounded-xl border border-blue-400/15 bg-blue-500/5 px-4 py-3 text-xs leading-5 text-slate-400">Owner admin uses the Koschei Web3 Hub Neon schema: plans, payment_requests, entitlements and web3_outputs. Verifying a payment request activates its output entitlement exactly once.</p><div className="flex flex-wrap justify-between gap-3"><button type="button" className="web3-button-secondary" onClick={() => void loadData()} disabled={loading}>{loading ? "Refreshing…" : "Refresh Neon data"}</button><button type="button" className="web3-button-secondary" onClick={() => void logout()}>Log out</button></div>{error && <p role="alert" className="text-xs font-bold text-rose-300">{error}</p>}<div className="grid gap-5 md:grid-cols-4">{[["Plans", plans.length], ["Payment requests", paymentRequests.length], ["Entitlements", entitlements.length], ["Web3 outputs", outputs.length]].map(([label, value]) => <div className="glass-card p-5" key={label}><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-3 text-xl font-black text-white">{value}</p></div>)}</div>
  <TableShell title="Plans"><table className="w-full text-left"><thead><tr><Cell>Name</Cell><Cell>Price</Cell><Cell>Quota</Cell><Cell>Status</Cell><Cell>Shopier</Cell></tr></thead><tbody>{plans.length ? plans.map((item) => <tr className="border-t border-white/10" key={item.id}><Cell>{item.name}</Cell><Cell>{money(item.price_try)}</Cell><Cell>{item.output_quota} outputs</Cell><Cell>{item.is_active ? "active" : "inactive"}</Cell><Cell><a className="text-blue-300 hover:text-blue-200" href={item.shopier_url} rel="noreferrer" target="_blank">Open ↗</a></Cell></tr>) : <Empty columns={5} label="No plans found." />}</tbody></table></TableShell>
  <TableShell title="Payment requests"><table className="w-full text-left"><thead><tr><Cell>Email</Cell><Cell>Name</Cell><Cell>Plan</Cell><Cell>Amount</Cell><Cell>Status</Cell><Cell>Created</Cell><Cell>Reviewed</Cell><Cell>Actions</Cell></tr></thead><tbody>{paymentRequests.length ? paymentRequests.map((item) => <tr className="border-t border-white/10" key={String(item.id)}><Cell>{String(item.email)}</Cell><Cell>{String(item.full_name)}</Cell><Cell>{String(item.plan)}</Cell><Cell>{money(item.amount_try)}</Cell><Cell>{String(item.status)}</Cell><Cell>{date(item.created_at)}</Cell><Cell>{date(item.reviewed_at)}</Cell><Cell>{item.status === "pending" ? <span className="flex gap-2"><button className="text-emerald-300 hover:text-emerald-200" disabled={loading} onClick={() => void review(item.id, "manual_verified")}>Verify</button><button className="text-rose-300 hover:text-rose-200" disabled={loading} onClick={() => void review(item.id, "rejected")}>Reject</button></span> : "—"}</Cell></tr>) : <Empty columns={8} label="No payment requests found." />}</tbody></table></TableShell>
  <TableShell title="Entitlements"><table className="w-full text-left"><thead><tr><Cell>Email</Cell><Cell>Plan</Cell><Cell>Payment request</Cell><Cell>Remaining</Cell><Cell>Status</Cell><Cell>Created</Cell></tr></thead><tbody>{entitlements.length ? entitlements.map((item) => <tr className="border-t border-white/10" key={String(item.id)}><Cell>{String(item.email)}</Cell><Cell>{String(item.plan_name)}</Cell><Cell>{String(item.payment_request_id)}</Cell><Cell>{String(item.outputs_remaining)} / {String(item.outputs_total)}</Cell><Cell>{String(item.status)}</Cell><Cell>{date(item.created_at)}</Cell></tr>) : <Empty columns={6} label="No entitlements found." />}</tbody></table></TableShell>
  <TableShell title="Web3 outputs"><table className="w-full text-left"><thead><tr><Cell>Email</Cell><Cell>Type</Cell><Cell>Title</Cell><Cell>Ecosystem</Cell><Cell>AI</Cell><Cell>Fallback</Cell><Cell>Remaining</Cell><Cell>Created</Cell></tr></thead><tbody>{outputs.length ? outputs.map((item) => <tr className="border-t border-white/10" key={String(item.id)}><Cell>{String(item.email)}</Cell><Cell>{String(item.output_type)}</Cell><Cell>{item.title ? String(item.title) : "—"}</Cell><Cell>{item.ecosystem ? String(item.ecosystem) : "—"}</Cell><Cell>{item.used_ai ? "yes" : "no"}</Cell><Cell>{item.used_fallback ? "yes" : "no"}</Cell><Cell>{String(item.outputs_remaining)}</Cell><Cell>{date(item.created_at)}</Cell></tr>) : <Empty columns={8} label="No generated outputs found." />}</tbody></table></TableShell>
  <section className="glass-card p-5"><h2 className="font-bold text-white">Enabled feature flags</h2><p className="mt-2 text-xs text-slate-400">Enabled chains: {enabledChains.join(", ") || "none"}</p><div className="mt-4 flex flex-wrap gap-2">{enabledFlags.map(([flag]) => <FeatureFlagBadge key={flag} label={flag} enabled />)}</div></section></div>;
}
