"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { FeatureFlagBadge } from "@/components/FeatureFlagBadge";

type Row = Record<string, unknown>;
type Product = Row & { id: string; name: string; price_try_cents: number | string; output_quota: number | string; shopier_url: string };
const chainFlags: Record<string, string> = { FEATURE_SOLANA: "Solana", FEATURE_BASE: "Base", FEATURE_ARBITRUM: "Arbitrum", FEATURE_POLYGON: "Polygon", FEATURE_OPTIMISM: "Optimism", FEATURE_ETHEREUM: "Ethereum" };
const money = (value: unknown) => new Intl.NumberFormat("tr-TR", { style: "currency", currency: "TRY" }).format(Number(value) / 100);
const date = (value: unknown) => typeof value === "string" ? new Date(value).toLocaleString("tr-TR") : "—";
function Cell({ children }: { children: React.ReactNode }) { return <td className="whitespace-nowrap px-3 py-3 text-xs text-slate-300">{children ?? "—"}</td>; }
function Empty({ columns, label }: { columns: number; label: string }) { return <tr><td colSpan={columns} className="px-3 py-5 text-center text-xs text-slate-500">{label}</td></tr>; }
function TableShell({ title, children }: { title: string; children: React.ReactNode }) { return <section className="glass-card overflow-hidden"><h2 className="border-b border-white/10 px-5 py-4 font-bold text-white">{title}</h2><div className="overflow-x-auto">{children}</div></section>; }

export function AdminDashboard({ flags }: { flags: Record<string, boolean> }) {
  const [loggedIn, setLoggedIn] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const [products, setProducts] = useState<Product[]>([]); const [orders, setOrders] = useState<Row[]>([]); const [entitlements, setEntitlements] = useState<Row[]>([]); const [outputs, setOutputs] = useState<Row[]>([]);
  const loadData = useCallback(async () => { setLoading(true); setError(""); try { const responses = await Promise.all([fetch("/api/products"), fetch("/api/admin/orders"), fetch("/api/admin/entitlements"), fetch("/api/admin/outputs")]); if (responses.some((response) => !response.ok)) throw new Error("Admin data request failed."); const [productData, orderData, entitlementData, outputData] = await Promise.all(responses.map((response) => response.json())); setProducts(productData.products); setOrders(orderData.orders); setEntitlements(entitlementData.entitlements); setOutputs(outputData.outputs); } catch { setError("Could not load Neon admin data. Confirm the admin session, DATABASE_URL, and migration status."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timeout = window.setTimeout(() => { void fetch("/api/admin/session").then((response) => { setLoggedIn(response.ok); if (response.ok) void loadData(); }); }, 0); return () => window.clearTimeout(timeout); }, [loadData]);
  async function login(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const data = new FormData(event.currentTarget); try { const response = await fetch("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: data.get("email"), password: data.get("password") }) }); if (!response.ok) throw new Error("Login failed."); setLoggedIn(true); await loadData(); } catch { setError("Login failed. Unauthorized access is not permitted."); } }
  async function logout() { await fetch("/api/admin/logout", { method: "POST" }); setLoggedIn(false); setError(""); }
  if (!loggedIn) return <form onSubmit={login} className="glass-card mx-auto mt-9 max-w-md space-y-4 p-6"><p className="text-sm font-bold leading-6 text-rose-200">Owner-only area. Unauthorized access is not permitted.</p><label className="web3-label">Email<input name="email" type="email" className="web3-input" required /></label><label className="web3-label">Password<input name="password" type="password" className="web3-input" required /></label><button className="web3-button">Sign in</button>{error && <p role="alert" className="text-xs leading-5 text-rose-300">{error}</p>}</form>;
  const enabledChains = Object.entries(chainFlags).filter(([flag]) => flags[flag]).map(([, label]) => label); const enabledFlags = Object.entries(flags).filter(([, enabled]) => enabled);
  return <div className="mt-9 space-y-6"><div className="flex flex-wrap justify-between gap-3"><button type="button" className="web3-button-secondary" onClick={() => void loadData()} disabled={loading}>{loading ? "Refreshing…" : "Refresh Neon data"}</button><button type="button" className="web3-button-secondary" onClick={() => void logout()}>Log out</button></div>{error && <p role="alert" className="text-xs font-bold text-rose-300">{error}</p>}<div className="grid gap-5 md:grid-cols-4">{[["Products", products.length], ["Orders", orders.length], ["Entitlements", entitlements.length], ["Generated outputs", outputs.length]].map(([label, value]) => <div className="glass-card p-5" key={label}><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-3 text-xl font-black text-white">{value}</p></div>)}</div>
  <TableShell title="Products"><table className="w-full text-left"><thead><tr className="text-[10px] uppercase text-slate-500"><Cell>Name</Cell><Cell>Price</Cell><Cell>Quota</Cell><Cell>Shopier</Cell></tr></thead><tbody>{products.length ? products.map((item) => <tr className="border-t border-white/10" key={item.id}><Cell>{item.name}</Cell><Cell>{money(item.price_try_cents)}</Cell><Cell>{item.output_quota} outputs</Cell><Cell><a className="text-cyan-300 hover:text-cyan-200" href={item.shopier_url} target="_blank" rel="noreferrer">Open product</a></Cell></tr>) : <Empty columns={4} label="No active products found." />}</tbody></table></TableShell>
  <TableShell title="Orders"><table className="w-full text-left"><thead><tr><Cell>Customer</Cell><Cell>Product</Cell><Cell>Provider</Cell><Cell>Amount</Cell><Cell>Status</Cell><Cell>Created</Cell></tr></thead><tbody>{orders.length ? orders.map((item) => <tr className="border-t border-white/10" key={String(item.id)}><Cell>{String(item.customer_email)}</Cell><Cell>{String(item.product_name)}</Cell><Cell>{String(item.provider)}</Cell><Cell>{money(item.amount_try_cents)}</Cell><Cell>{String(item.status)}</Cell><Cell>{date(item.created_at)}</Cell></tr>) : <Empty columns={6} label="No orders found." />}</tbody></table></TableShell>
  <TableShell title="Entitlements and remaining output rights"><table className="w-full text-left"><thead><tr><Cell>Customer</Cell><Cell>Product</Cell><Cell>Total</Cell><Cell>Remaining rights</Cell><Cell>Status</Cell><Cell>Created</Cell></tr></thead><tbody>{entitlements.length ? entitlements.map((item) => <tr className="border-t border-white/10" key={String(item.id)}><Cell>{String(item.customer_email)}</Cell><Cell>{String(item.product_name)}</Cell><Cell>{String(item.outputs_total)}</Cell><Cell><strong className="text-emerald-300">{String(item.outputs_remaining)}</strong></Cell><Cell>{String(item.status)}</Cell><Cell>{date(item.created_at)}</Cell></tr>) : <Empty columns={6} label="No verified entitlements found." />}</tbody></table></TableShell>
  <TableShell title="Generated outputs"><table className="w-full text-left"><thead><tr><Cell>Customer</Cell><Cell>Type</Cell><Cell>Remaining rights</Cell><Cell>AI</Cell><Cell>Fallback</Cell><Cell>Created</Cell></tr></thead><tbody>{outputs.length ? outputs.map((item) => <tr className="border-t border-white/10" key={String(item.id)}><Cell>{String(item.customer_email)}</Cell><Cell>{String(item.output_type)}</Cell><Cell>{String(item.outputs_remaining)}</Cell><Cell>{item.used_ai === true || item.used_ai === "true" ? "Yes" : "No"}</Cell><Cell>{item.used_fallback === true || item.used_fallback === "true" ? "Yes" : "No"}</Cell><Cell>{date(item.created_at)}</Cell></tr>) : <Empty columns={6} label="No database-backed outputs found." />}</tbody></table></TableShell>
  <div className="grid gap-6 lg:grid-cols-2"><div className="glass-card p-6"><h2 className="font-bold text-white">Enabled feature flags</h2><div className="mt-4 flex flex-wrap gap-2">{enabledFlags.length ? enabledFlags.map(([label]) => <FeatureFlagBadge key={label} label={label} enabled />) : <p className="text-sm text-slate-400">No feature flags enabled.</p>}</div></div><div className="glass-card p-6"><h2 className="font-bold text-white">Enabled chains</h2><p className="mt-4 text-sm leading-6 text-slate-300">{enabledChains.length ? enabledChains.join(" · ") : "No chains enabled. Configure feature flags on the server."}</p></div></div></div>;
}
