"use client";

/* eslint-disable @next/next/no-img-element */

import type { QuoteData } from "@/lib/types";
import { calculateTotal, HS_GTIP_DISCLAIMER, PLATFORM_DISCLAIMER } from "@/lib/quote";

const money = (amount: number, currency: string) => new Intl.NumberFormat("en-US", { style: "currency", currency }).format(amount);

export function PrintableQuote({ quote }: { quote: QuoteData }) {
  const { company, buyer, product } = quote;
  const total = calculateTotal(product);
  return <article className="printable-quote mx-auto min-h-[1120px] max-w-[800px] border border-slate-200 bg-white p-4 shadow-xl sm:p-12">
    <header className="avoid-print-break flex flex-col justify-between gap-5 border-b-2 border-slate-950 pb-6 sm:flex-row sm:items-start">
      <div className="flex items-start gap-3 sm:gap-4">{company.logoUrl ? <img src={company.logoUrl} alt={`${company.name} logo`} className="h-12 w-12 shrink-0 rounded-lg object-contain sm:h-14 sm:w-14"/> : <span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-lg bg-slate-950 text-base font-black text-cyan-400 sm:h-14 sm:w-14 sm:text-lg">{company.name.slice(0,2).toUpperCase()}</span>}<div className="min-w-0"><h1 className="break-words text-xl font-black tracking-tight text-slate-950 sm:text-2xl">{company.name}</h1><p className="mt-1 max-w-sm break-words text-xs leading-5 text-slate-500">{company.address}</p><p className="mt-1 break-all text-xs text-slate-500">{company.website}</p></div></div>
      <div className="shrink-0 sm:text-right"><p className="text-xl font-black tracking-widest text-slate-950">QUOTATION</p><p className="mt-2 text-xs font-bold text-cyan-700">{quote.quotationNumber}</p><p className="mt-1 text-xs text-slate-500">{new Date(quote.createdAt).toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })}</p></div>
    </header>
    <section className="avoid-print-break grid gap-5 border-b border-slate-200 py-6 sm:grid-cols-2"><div><Label>Prepared for</Label><p className="mt-2 text-base font-black">{buyer.company}</p><p className="mt-1 text-sm text-slate-600">Attn: {buyer.contactName}</p><p className="text-sm text-slate-600">{buyer.country}</p><p className="break-all text-sm text-slate-600">{buyer.email}</p></div><div><Label>Prepared by</Label><p className="mt-2 text-base font-black">{company.contactPerson}</p><p className="break-all mt-1 text-sm text-slate-600">{company.email}</p><p className="text-sm text-slate-600">{company.phone}</p></div></section>
    <section className="py-6"><h2 className="mb-4 text-sm font-black tracking-widest text-slate-950">COMMERCIAL OFFER</h2><div className="avoid-print-break overflow-hidden rounded-lg border border-slate-200"><table className="quote-table w-full table-fixed text-left text-xs sm:text-sm"><thead className="bg-slate-950 text-[10px] tracking-wide text-white sm:text-xs"><tr><th className="w-[43%] px-2 py-3 sm:px-4">PRODUCT</th><th className="w-[17%] px-2 py-3 sm:px-4">QTY</th><th className="w-[20%] px-2 py-3 text-right sm:px-4">UNIT PRICE</th><th className="w-[20%] px-2 py-3 text-right sm:px-4">TOTAL</th></tr></thead><tbody><tr className="align-top"><td className="break-words px-2 py-4 sm:px-4"><strong>{product.name}</strong><p className="mt-1 text-xs leading-5 text-slate-500">{product.category}</p><p className="mt-2 text-xs leading-5 text-slate-500">{quote.productDescriptionEn}</p></td><td className="break-words px-2 py-4 sm:px-4">{product.quantity} {product.unit}</td><td className="break-words px-2 py-4 text-right sm:px-4">{money(product.unitPrice, product.currency)}</td><td className="break-words px-2 py-4 text-right font-bold sm:px-4">{money(total, product.currency)}</td></tr></tbody></table></div><div className="avoid-print-break flex justify-end"><div className="mt-4 flex w-full max-w-xs justify-between gap-3 rounded-lg bg-slate-100 px-4 py-3 text-sm font-black sm:text-base"><span><span className="block">Total Amount</span><span className="mt-1 block text-[10px] font-bold text-slate-500">{product.quantity} {product.unit} × {money(product.unitPrice, product.currency)}</span></span><span className="shrink-0">{money(total, product.currency)}</span></div></div></section>
    <section className="avoid-print-break grid gap-x-6 gap-y-4 rounded-lg bg-slate-50 p-5 text-sm sm:grid-cols-2"><Detail label="Incoterm" value={product.incoterm}/><Detail label="Delivery time" value={product.deliveryTime}/><Detail label="Payment terms" value={product.paymentTerms}/><Detail label="Offer validity" value={`${product.validityDays} days`}/><Detail label="Estimated HS/GTIP code" value={product.hsCode || "Not specified"}/><Detail label="Packaging" value={product.packagingDetails}/>{product.notes && <div className="sm:col-span-2"><Detail label="Additional notes" value={product.notes}/></div>}</section>
    <section className="py-6"><Label>Offer message</Label><p className="mt-3 whitespace-pre-line text-sm leading-6 text-slate-700">{quote.englishOfferText}</p></section>
    {quote.exportNotes && <section className="avoid-print-break pb-6"><Label>Export notes</Label><p className="mt-3 whitespace-pre-line text-xs leading-5 text-slate-600">{quote.exportNotes}</p></section>}
    <footer className="avoid-print-break border-t border-slate-200 pt-4 text-[10px] leading-4 text-slate-500"><p className="mb-2 font-black uppercase tracking-widest text-slate-700">Export &amp; Platform Disclaimer</p><div className="space-y-1"><p><strong>HS/GTIP warning:</strong> {HS_GTIP_DISCLAIMER}</p><p><strong>Platform notice:</strong> {PLATFORM_DISCLAIMER}</p></div></footer>
  </article>;
}
function Label({ children }: { children: React.ReactNode }) { return <p className="text-[10px] font-black uppercase tracking-widest text-cyan-700">{children}</p>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><Label>{label}</Label><p className="mt-1 break-words leading-5 text-slate-700">{value}</p></div>; }
