"use client";

import { useRouter } from "next/navigation";
import { useEffect, useState, type FormEvent, type InputHTMLAttributes, type TextareaHTMLAttributes } from "react";
import { Button } from "@/components/Button";
import { Card } from "@/components/Card";
import { generateEnglishOfferText, generateFollowUpMessage, generateQuotationNumber, getLatestQuoteFromLocalStorage, saveQuoteToLocalStorage } from "@/lib/quote";
import type { BuyerInfo, CompanyInfo, ProductInfo } from "@/lib/types";

const defaultCompany: CompanyInfo = { name: "", contactPerson: "", email: "", phone: "", address: "", website: "", logoUrl: "" };
const defaultBuyer: BuyerInfo = { company: "", contactName: "", country: "", email: "" };
const defaultProduct: ProductInfo = { name: "", category: "", descriptionTr: "", quantity: 1, unit: "pcs", unitPrice: 0, currency: "USD", incoterm: "EXW", deliveryTime: "2-3 weeks after order confirmation", paymentTerms: "50% advance payment, 50% before shipment", validityDays: 15, hsCode: "", packagingDetails: "", notes: "" };
const sampleCompany: CompanyInfo = { name: "Anadolu Seramik Dış Ticaret Ltd. Şti.", contactPerson: "Elif Yılmaz", email: "elif.yilmaz@anadoluseramik.com", phone: "+90 532 555 24 18", address: "Organize Sanayi Bölgesi 4. Cadde No: 18, Kütahya, Türkiye", website: "https://www.anadoluseramik.com", logoUrl: "" };
const sampleBuyer: BuyerInfo = { company: "Nordic Home Trading GmbH", contactName: "Anna Müller", country: "Germany", email: "anna.mueller@nordichome.de" };
const sampleProduct: ProductInfo = { name: "Handmade Ceramic Dinnerware Set", category: "Tableware / Ceramic Products", descriptionTr: "24 parçalı, el işçiliği seramik yemek takımı. Gıda ile temasa uygun sır kaplama ve ihracata uygun korumalı ambalaj.", quantity: 250, unit: "sets", unitPrice: 38.5, currency: "USD", incoterm: "FOB", deliveryTime: "3-4 weeks after order confirmation", paymentTerms: "50% advance payment, 50% before shipment", validityDays: 15, hsCode: "6912.00", packagingDetails: "Each set is packed in a protective export carton. 20 cartons per pallet.", notes: "Product colours can be confirmed before production." };

function Field({ label, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="block"><span className="mb-2 block text-sm font-bold text-slate-700">{label}</span><input {...props} className="min-h-12 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 placeholder:text-slate-400 outline-none focus:border-cyan-600 focus:ring-2 focus:ring-cyan-100" /></label>; }
function Area({ label, ...props }: TextareaHTMLAttributes<HTMLTextAreaElement> & { label: string }) { return <label className="block"><span className="mb-2 block text-sm font-bold text-slate-700">{label}</span><textarea {...props} className="min-h-24 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 placeholder:text-slate-400 outline-none focus:border-cyan-600 focus:ring-2 focus:ring-cyan-100" /></label>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="block"><span className="mb-2 block text-sm font-bold text-slate-700">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="min-h-12 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none focus:border-cyan-600 focus:ring-2 focus:ring-cyan-100">{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }

export function QuoteForm() {
  const router = useRouter();
  const [company, setCompany] = useState(defaultCompany);
  const [buyer, setBuyer] = useState(defaultBuyer);
  const [product, setProduct] = useState(defaultProduct);
  useEffect(() => { if (new URLSearchParams(window.location.search).get("edit") !== "latest") return; const latest = getLatestQuoteFromLocalStorage(); if (latest) { setCompany(latest.company); setBuyer(latest.buyer); setProduct(latest.product); } }, []);
  const companyField = (key: keyof CompanyInfo) => ({ value: company[key] ?? "", onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setCompany({ ...company, [key]: event.target.value }) });
  const buyerField = (key: keyof BuyerInfo) => ({ value: buyer[key], onChange: (event: React.ChangeEvent<HTMLInputElement>) => setBuyer({ ...buyer, [key]: event.target.value }) });
  const productField = (key: keyof ProductInfo) => ({ value: product[key] ?? "", onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setProduct({ ...product, [key]: event.target.value }) });
  const numberField = (key: "quantity" | "unitPrice" | "validityDays") => ({ value: product[key], min: key === "unitPrice" ? 0.01 : 1, step: key === "unitPrice" ? "0.01" : "1", onChange: (event: React.ChangeEvent<HTMLInputElement>) => setProduct({ ...product, [key]: Number(event.target.value) }) });

  function fillSampleData() { setCompany(sampleCompany); setBuyer(sampleBuyer); setProduct(sampleProduct); }
  function submit(event: FormEvent) {
    event.preventDefault();
    const quote = { quotationNumber: generateQuotationNumber(), createdAt: new Date().toISOString(), company, buyer, product, englishOfferText: generateEnglishOfferText(company, buyer, product), followUpMessage: generateFollowUpMessage(buyer, product) };
    saveQuoteToLocalStorage(quote);
    router.push("/quote/preview");
  }

  return <form onSubmit={submit} className="space-y-6">
    <div className="flex flex-col gap-3 rounded-2xl border border-cyan-200 bg-cyan-50 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black text-slate-950">Demo için hızlı başlangıç</p><p className="mt-1 text-sm leading-6 text-slate-700">Gerçekçi örnek ihracat verilerini tek tıkla forma ekleyin.</p></div><Button type="button" variant="secondary" onClick={fillSampleData} className="shrink-0">Örnek Veri Doldur</Button></div>
    <Card className="p-5 sm:p-6"><SectionTitle number="01" title="Firma bilgileri" copy="Teklifi gönderen şirketin kurumsal bilgileri."/><div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="Firma adı" placeholder="Örn. Anadolu Seramik Dış Ticaret Ltd. Şti." required {...companyField("name")}/><Field label="Yetkili kişi" placeholder="Örn. Elif Yılmaz" required {...companyField("contactPerson")}/><Field label="E-posta" type="email" placeholder="elif@firmanız.com" required {...companyField("email")}/><Field label="Telefon / WhatsApp" type="tel" placeholder="+90 5xx xxx xx xx" required {...companyField("phone")}/><Field label="Web sitesi" type="url" placeholder="https://www.firmaniz.com" required {...companyField("website")}/><Field label="Logo URL (opsiyonel)" type="url" placeholder="https://.../logo.png" {...companyField("logoUrl")}/><div className="md:col-span-2"><Area label="Adres" placeholder="Firma adresinizi yazın" required {...companyField("address")}/></div></div></Card>
    <Card className="p-5 sm:p-6"><SectionTitle number="02" title="Alıcı bilgileri" copy="Teklifin ulaşacağı müşteri ve ülke bilgileri."/><div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="Alıcı firma" placeholder="Örn. Nordic Home Trading GmbH" required {...buyerField("company")}/><Field label="Alıcı yetkili adı" placeholder="Örn. Anna Müller" required {...buyerField("contactName")}/><Field label="Alıcı ülke" placeholder="Örn. Germany" required {...buyerField("country")}/><Field label="Alıcı e-posta" type="email" placeholder="anna@alici-firma.com" required {...buyerField("email")}/></div></Card>
    <Card className="p-5 sm:p-6"><SectionTitle number="03" title="Ürün ve ticari koşullar" copy="Fiyatlandırma ve teslimat için gereken temel detaylar."/><div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="Ürün adı" placeholder="Örn. Handmade Ceramic Dinnerware Set" required {...productField("name")}/><Field label="Ürün kategorisi" placeholder="Örn. Tableware / Ceramic Products" required {...productField("category")}/><div className="md:col-span-2"><Area label="Türkçe ürün açıklaması" placeholder="Ürünün öne çıkan özelliklerini ve kapsamını yazın" required {...productField("descriptionTr")}/></div><Field label="Miktar" type="number" required {...numberField("quantity")}/><Field label="Birim" placeholder="Örn. pcs, kg, sets, boxes" required {...productField("unit")}/><Field label="Birim fiyat" type="number" required {...numberField("unitPrice")}/><Select label="Para birimi" value={product.currency} options={["USD", "EUR", "TRY"]} onChange={(currency) => setProduct({ ...product, currency: currency as ProductInfo["currency"] })}/><Select label="Incoterm" value={product.incoterm} options={["EXW", "FOB", "CIF", "DAP"]} onChange={(incoterm) => setProduct({ ...product, incoterm: incoterm as ProductInfo["incoterm"] })}/><Field label="Teslimat süresi" placeholder="Örn. 3-4 weeks after order confirmation" required {...productField("deliveryTime")}/><Field label="Ödeme koşulları" placeholder="Örn. 50% advance, 50% before shipment" required {...productField("paymentTerms")}/><Field label="Geçerlilik süresi (gün)" type="number" required {...numberField("validityDays")}/></div></Card>
    <Card className="p-5 sm:p-6"><SectionTitle number="04" title="İhracat yardımcı bilgileri" copy="Gümrük ve paketleme görüşmelerinde kullanabileceğiniz ek alanlar."/><div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="Tahmini HS / GTIP kodu (opsiyonel)" placeholder="Örn. 6912.00" {...productField("hsCode")}/><Field label="Paketleme detayları" placeholder="Örn. Export carton, 20 cartons per pallet" required {...productField("packagingDetails")}/><div className="md:col-span-2"><Area label="Notlar" placeholder="Teklife eklemek istediğiniz ilave notlar..." {...productField("notes")}/></div></div></Card>
    <div className="flex flex-col items-end gap-3"><p className="text-right text-xs leading-5 text-slate-600">Devam ederek bilgilerin bu tarayıcıda yerel olarak saklanmasını kabul edersiniz.</p><Button type="submit" className="w-full sm:w-auto">İngilizce Teklifi Hazırla <span className="ml-1">→</span></Button></div>
  </form>;
}
function SectionTitle({ number, title, copy }: { number: string; title: string; copy: string }) { return <div className="flex gap-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-slate-950 text-xs font-black text-cyan-400">{number}</span><div><h2 className="text-lg font-black text-slate-950">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-600">{copy}</p></div></div>; }
