"use client";

import { FormEvent, useMemo, useState } from "react";
import { JsonPreview } from "@/components/JsonPreview";
import { SiteHeader } from "@/components/SiteHeader";

type Form = { project: string; ecosystem: string; assetType: string; name: string; category: string; description: string; utility: string; attributes: string; externalUrl: string; imageUrl: string; riskNotes: string };
type Notice = { message: string; tone: "success" | "error" } | null;

const initial: Form = { project: "", ecosystem: "Solana", assetType: "Game Item", name: "", category: "", description: "", utility: "", attributes: "", externalUrl: "", imageUrl: "", riskNotes: "" };
const sample: Form = { project: "Koschei Arena", ecosystem: "Solana", assetType: "Game Item", name: "Shadow Reactor Blade", category: "Weapon", description: "A reactor-forged arena weapon concept designed for competitive Web3 game inventory metadata.", utility: "In-game item metadata concept for a collectible arena weapon. No token, contract, or gameplay entitlement is created by this draft.", attributes: "rarity: legendary, class: reactor blade, power: 92, element: shadow", externalUrl: "", imageUrl: "", riskNotes: "Concept metadata only. Verify balancing, artwork rights, and collection details before publishing." };

export default function Builder() {
  const [form, setForm] = useState(initial);
  const [notice, setNotice] = useState<Notice>(null);
  const [generating, setGenerating] = useState(false);
  const [generationSource, setGenerationSource] = useState<"AI output" | "Fallback output" | null>(null);
  const metadata = useMemo(() => ({ project: form.project, ecosystem: form.ecosystem, assetType: form.assetType, name: form.name, category: form.category, description: form.description, utility: form.utility, attributes: form.attributes.split(",").map((attribute) => attribute.trim()).filter(Boolean), external_url: form.externalUrl, image: form.imageUrl, riskNotes: form.riskNotes, notice: "Concept metadata only. No token or contract is created or deployed." }), [form]);
  const json = JSON.stringify(metadata, null, 2);

  function update(key: keyof Form, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  function fillSample() { setForm(sample); setGenerationSource(null); setNotice({ tone: "success", message: "Sample Web3 game asset loaded. JSON preview updated." }); }
  function save(event: FormEvent) { event.preventDefault(); try { const old = JSON.parse(localStorage.getItem("koschei_assets") || "[]") as unknown[]; localStorage.setItem("koschei_assets", JSON.stringify([...old, { ...metadata, createdAt: new Date().toISOString() }])); setNotice({ tone: "success", message: "Generated asset saved to this browser's localStorage." }); } catch { setNotice({ tone: "error", message: "Asset could not be saved in this browser." }); } }
  async function copyJson() { try { await navigator.clipboard.writeText(json); setNotice({ tone: "success", message: "JSON copied to clipboard." }); } catch { setNotice({ tone: "error", message: "JSON could not be copied. Check browser clipboard permissions." }); } }
  async function generate() { setGenerating(true); setNotice(null); try { const response = await fetch("/api/ai/web3-generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode: "description", payload: form }) }); if (!response.ok) throw new Error("Generation request failed."); const data = await response.json() as { text?: string; usedFallback?: boolean }; if (!data.text) throw new Error("Generation response was empty."); update("description", data.text); setGenerationSource(data.usedFallback ? "Fallback output" : "AI output"); } catch { setGenerationSource("Fallback output"); update("description", "Project summary concept: Add verified project facts, intended utility, and ecosystem context to generate a tailored draft.\n\nReview this fallback draft before publishing."); } finally { setGenerating(false); } }
  function download() { try { const url = URL.createObjectURL(new Blob([json], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${form.name || "koschei-asset"}.json`; anchor.click(); URL.revokeObjectURL(url); setNotice({ tone: "success", message: "JSON download started." }); } catch { setNotice({ tone: "error", message: "JSON download could not be started in this browser." }); } }

  return <main className="web3-page"><SiteHeader /><section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p className="eyebrow">No-code output studio</p><h1 className="mt-4 text-4xl font-black text-white">Web3 Asset Builder</h1><p className="mt-4 text-sm text-slate-400">Create metadata concepts only. No tokens, contracts or private keys are used.</p><div className="mt-6 flex flex-wrap gap-3"><button className="web3-button-secondary" type="button" onClick={fillSample}>Fill Sample Data</button></div>{notice && <p role="status" className={`mt-4 text-sm font-bold ${notice.tone === "success" ? "text-emerald-300" : "text-rose-300"}`}>{notice.message}</p>}<div className="mt-9 grid gap-7 lg:grid-cols-2"><form onSubmit={save} className="glass-card grid gap-4 p-6 sm:grid-cols-2">{([['Project name', 'project'], ['Asset name', 'name'], ['Category', 'category'], ['External URL', 'externalUrl'], ['Image URL', 'imageUrl']] as [string, keyof Form][]).map(([label, key]) => <label className="web3-label" key={key}>{label}<input className="web3-input" value={form[key]} onChange={(event) => update(key, event.target.value)} required={key === "project" || key === "name"} /></label>)}<label className="web3-label">Ecosystem<select className="web3-input" value={form.ecosystem} onChange={(event) => update("ecosystem", event.target.value)}>{["Solana", "Base", "Arbitrum", "Polygon", "Optimism", "Ethereum"].map((ecosystem) => <option key={ecosystem}>{ecosystem}</option>)}</select></label><label className="web3-label">Asset type<select className="web3-input" value={form.assetType} onChange={(event) => update("assetType", event.target.value)}>{["Game Item", "NFT Collection", "Token Concept", "Launch Page"].map((type) => <option key={type}>{type}</option>)}</select></label>{([['Description', 'description'], ['Utility', 'utility'], ['Attributes (comma separated)', 'attributes'], ['Risk notes', 'riskNotes']] as [string, keyof Form][]).map(([label, key]) => <label className="web3-label sm:col-span-2" key={key}>{label}<textarea className="web3-input min-h-20" value={form[key]} onChange={(event) => update(key, event.target.value)} /></label>)}<div className="flex flex-wrap gap-3 sm:col-span-2"><button className="web3-button" type="submit">Save generated asset</button><button className="web3-button-secondary" type="button" onClick={generate} disabled={generating}>{generating ? "Generating…" : "AI Generate Description"}</button></div>{generationSource && <p className="text-xs font-bold text-blue-200 sm:col-span-2">{generationSource}</p>}</form><div><div className="mb-3 flex flex-wrap gap-3"><button type="button" onClick={copyJson} className="web3-button-secondary">Copy JSON</button><button type="button" onClick={download} className="web3-button-secondary">Download JSON</button></div><JsonPreview value={metadata} /></div></div></section></main>;
}
