"use client";
import { useState } from "react";

export default function SupplierOutreachClient({ initialLeads, braveConfigured, togetherConfigured, dbConfigured, fallbackPassword }: any) {
  const [leads, setLeads] = useState<any[]>(initialLeads);
  const [error, setError] = useState("");
  const [keywords, setKeywords] = useState("seed cleaning machine manufacturer China");
  const [productCategory, setProductCategory] = useState("Seed cleaning machines");
  const post = async (path: string, payload: any) => {
    const res = await fetch(path, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...payload, password: fallbackPassword }) });
    const data = await res.json(); if (!res.ok) throw new Error(data.error || "Request failed"); return data;
  };
  const refresh = async ()=> location.reload();
  return <main className="page-stack"><h1>Supplier Outreach</h1>
  {!braveConfigured && <p>Brave Search API yapılandırılmamış</p>}{!togetherConfigured && <p>Together API yapılandırılmamış</p>}{!dbConfigured && <p>Henüz kayıt yok</p>}{error && <p>{error}</p>}
  <section className="card"><h2>Discovery</h2><input value={productCategory} onChange={(e)=>setProductCategory(e.target.value)} /><input value={keywords} onChange={(e)=>setKeywords(e.target.value)} /><button className="btn" onClick={async()=>{try{await post('/api/owner/supplier-outreach/discover',{product_category:productCategory,keywords,target_country:'China',target_platform:'mixed'});await refresh();}catch(e:any){setError(e.message)}}}>Run Discovery</button></section>
  <section className="card">{leads.length===0?<p>Henüz kayıt yok</p>:leads.map((l)=><article key={l.id} className="card"><p><strong>{l.company_name||"Firma adı doğrulanmadı"}</strong></p><p>{l.platform} | <a href={l.source_url} target="_blank" rel="noreferrer">{l.source_url}</a></p><p>confidence:{l.confidence} manufacturer_score:{String(l.manufacturer_score??"-")} risk_score:{String(l.risk_score??"-")}</p><p>likely_manufacturer:{String(l.likely_manufacturer)} likely_trader:{String(l.likely_trader)}</p><p>risk_notes:{l.risk_notes||"-"}</p><p>recommended_action:{l.recommended_action||"-"}</p><p>latest outreach message: {l.body || "-"}</p><p>event history: {l.event_history || "-"}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn" onClick={async()=>{try{await post('/api/owner/supplier-outreach/analyze',{supplier_lead_id:l.id});await refresh();}catch(e:any){setError(e.message)}}}>Analyze with AI</button><button className="btn" onClick={async()=>{try{await post('/api/owner/supplier-outreach/generate-message',{supplier_lead_id:l.id});await refresh();}catch(e:any){setError(e.message)}}}>Generate Message</button><button className="btn" onClick={async()=>{try{await post('/api/owner/supplier-outreach/approve-message',{message_id:l.message_id});await refresh();}catch(e:any){setError(e.message)}}}>Approve Message</button><button className="btn" onClick={async()=>{try{await post('/api/owner/supplier-outreach/mark-status',{supplier_lead_id:l.id,status:'sent'});await refresh();}catch(e:any){setError(e.message)}}}>Mark Sent</button><button className="btn" onClick={async()=>{try{await post('/api/owner/supplier-outreach/mark-status',{supplier_lead_id:l.id,status:'replied'});await refresh();}catch(e:any){setError(e.message)}}}>Mark Replied</button><button className="btn" onClick={async()=>{try{await post('/api/owner/supplier-outreach/mark-status',{supplier_lead_id:l.id,status:'rejected'});await refresh();}catch(e:any){setError(e.message)}}}>Reject Lead</button></div></article>)}</section></main>;
}
